### ISSUE TITLE
Setting priorities on components

### ISSUE THREAD

**Issue by m-aciek** [m-aciek/python-docs-weblate#4]
Automate setting priorities on components. Manually it's too much hussle.

**Comment by rffontenelle** [comment]
I came across with F-Droid's script for setting priority of docs in Weblate: https://gitlab.com/fdroid/fdroid-website/-/merge_requests/919

**Comment by m-aciek** [comment]
It looks like [component priority](https://docs.weblate.org/en/latest/admin/projects.html#priority) is separate from [strings priority](https://docs.weblate.org/en/latest/admin/translating.html#strings-prioritization). The linked script sets strings priorities.

Also Weblate Python API doesn't support components' priorities yet. HTTP API does though.

**Comment by m-aciek** [comment]
PR adding support for component's priority in the Weblate Python API: https://github.com/WeblateOrg/wlc/pull/454
